import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="kr">
            <body>
                <div className="kiosk-viewport">
                    <div className="kiosk-canvas">{children}</div>
                </div>
            </body>
        </html>
    );
}
